name: CI

on:
  push:
    branches:
      - main
      - SCRUM-*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      api:
        image: mwinteringham/restfulbooker:latest
        ports:
          - 3001:3001

    env:
      BASE_URL: http://localhost:3001/
      API_USERNAME: admin
      API_PASSWORD: password123

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          python -m pytest tests/ --cov=tests --cov-report=xml --cov-report=html --cov-report=term-missing

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30

      # Note: Codecov integration requires setting up codecov.io account
      # Uncomment when ready to integrate with Codecov
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     file: ./coverage.xml
      #     flags: unittests
      #     name: codecov-umbrella
      #     fail_ci_if_error: false

      # Note: PR coverage commenting requires additional setup
      # Uncomment when ready for automated PR comments
      # - name: Comment PR with coverage
      #   if: github.event_name == 'pull_request'
      #   uses: romeovs/lcov-reporter-action@v0.3.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     lcov-file: ./coverage.xml
